TIME: 2025-08-27T16:32:05.137154+00:00
SCRIPT: s2_collect
STEP: collect_for[Test Automation|poland-remote]

TRACEBACK:
Traceback (most recent call last):
  File "C:\Repo\auto_job_finder\src\s2_collect_links.py", line 264, in collect_for
    browser, context = launch_browser(headful=headful)
                       ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Repo\auto_job_finder\src\common.py", line 87, in launch_browser
    pw = sync_playwright().start()
  File "C:\Users\alexe\AppData\Roaming\Python\Python313\site-packages\playwright\sync_api\_context_manager.py", line 84, in start
    return self.__enter__()
           ~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\AppData\Roaming\Python\Python313\site-packages\playwright\sync_api\_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

